## Exercise Description:

Perform classification for the entire MNIST dataset based on the algorithms introduced: Use LDA for dimensionality reduction to 2 or 9 dimensions, classify the dimension-reduced data and compare this classification performance with that of using PCA


In [29]:
import numpy as np
from scipy.io import loadmat
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
from sklearn import svm
import time


from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report,
    accuracy_score
)
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

# Exercise 7: Support Vector Machine (SVM)

Perform classification for the entire MNIST dataset by using SVMs, e.g. functions in Scikit-learn or Matlab.


## Load data training and testing data


In [24]:
def create_complete_datasets(data_dict):
    '''
    Function for creating complete training and test sets containing
    all classes.
    '''
    #Empty list
    trainset = []
    traintargets =[]
    testset = []
    testtargets =[]
    
    #For each class
    for i in range(10):
        trainset.append(data_dict["train%d"%i])
        traintargets.append(np.full(len(data_dict["train%d"%i]),i))
        testset.append(data_dict["test%d"%i])
        testtargets.append(np.full(len(data_dict["test%d"%i]),i))
    
    #Concatenate into to complete datasets
    trainset = np.concatenate(trainset)
    traintargets = np.concatenate(traintargets)
    testset = np.concatenate(testset)
    testtargets = np.concatenate(testtargets)
    return trainset, traintargets, testset, testtargets

# Data path
data_path = "../Data/"
file = data_path+"mnist_all.mat"
data = loadmat(file)

#Complete training and test sets
train_set, train_targets, test_set, test_targets = create_complete_datasets(data)

# Scale the data
train_set = StandardScaler().fit_transform(train_set)
test_set = StandardScaler().fit_transform(test_set)

print(f"train_set: \n{train_set}, shape: {train_set.shape}")
print(f"train_targets: \n{train_targets}, shape: {train_targets.shape}")
print(f"test_set: \n{test_set}, shape: {test_set.shape}")
print(f"test_targets: \n{test_targets}, shape: {test_targets.shape}")

train_set: 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape: (60000, 784)
train_targets: 
[0 0 0 ... 9 9 9], shape: (60000,)
test_set: 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape: (10000, 784)
test_targets: 
[0 0 0 ... 9 9 9], shape: (10000,)


## Create and fit SVM on training data


In [ ]:
def separate_data(data,n):
    data_sep = []
    for i in range(n+1):
        data_sep.append(data[train_targets == i])
        
    return data_sep

In [31]:
# Use sklearn to fit data
clf_svm = svm.SVC()
clf_svm.fit(train_set,train_targets)

# Choose n components
n_components = 9

# PCA
pca = PCA(n_components=n_components)
pca_transform_train = pca.fit_transform(train_set)
pca_transform_test = pca.transform(test_set)
svm_pca = svm.SVC()
svm_pca.fit(pca_transform_train,train_targets)

# LDA
lda = LDA(n_components=n_components)
lda_transform_train = lda.fit_transform(train_set)
lda_transform_test = lda.transform(test_set)
svm_lda = svm.SVC()
svm_lda.fit(lda_transform_train,train_targets)


In [27]:
# Separating data
data1 = separate_data(pca_transform,pca_transform.shape[1])
data2 = separate_data(lda_transform,lda_transform.shape[1])

SVC()


## Test model on test set


In [30]:
# What is the accuracy on the test set?
predict_svm = clf_svm.predict(test_set)
accuracy_svm = clf_svm.accuracy_score()
score_svm = clf_svm.score(test_set)

AttributeError: 'SVC' object has no attribute 'accuracy_score'

## Plot Confusion matrix


In [5]:
# Does the confusion matrix show us any insights about the model performance?
cm_svm = confusion_matrix(test_targets,predict_svm)

## Comparing with PCA/LDA


In [6]:
# How does SVM compare to PCA and LDA (compare confusion matrices)
cm_svm_pca = confusion_matrix(test_targets, svm_pca.predict(pca_transform_test))
cm_svm_lda = confusion_matrix(test_targets, svm_lda.predict(lda_transform_test))