# Exercise lecture 8 - Multilayer Perceptron
Develop an MLP for the MNIST
database by using the dimension-reduced data from your work on Exercises 2 and 3. You can download the LDA projected data here.
Further, you can use 10-, 20- and 30-dimensional data generated by PCA and compare
their performance (at the same time, try various MLP architectures).

## Loading data

In [2]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.neural_network import MLPClassifier as MLPC
import time
import warnings

warnings.simplefilter(action='ignore') #Ignore warnings

def create_complete_datasets(data_dict):
    '''
    Function for creating complete training and test sets containing
    all classes.
    '''
    #Empty list
    trainset = []
    traintargets =[]
    testset = []
    testtargets =[]
    
    #For each class
    for i in range(10):
        trainset.append(data_dict["train%d"%i])
        traintargets.append(np.full(len(data_dict["train%d"%i]),i))
        testset.append(data_dict["test%d"%i])
        testtargets.append(np.full(len(data_dict["test%d"%i]),i))
    
    #Concatenate into to complete datasets
    trainset = np.concatenate(trainset)
    traintargets = np.concatenate(traintargets)
    testset = np.concatenate(testset)
    testtargets = np.concatenate(testtargets)
    return trainset, traintargets, testset, testtargets

file = "Data/mnist_all.mat"
data = loadmat(file)

#Complete training and test sets
train_set, train_targets, test_set, test_targets = create_complete_datasets(data)
train_set = train_set/255
test_set = test_set/255
classes = np.arange(10)

print(f"Classes: \n{classes}")
print(f"train_targets: \n{train_targets}, shape: {train_targets.shape}")
print(f"train_set: \n{train_set}, shape: {train_set.shape}")
print(f"test_targets: \n{test_targets}, shape: {test_targets.shape}")
print(f"test_set: \n{test_set}, shape: {test_set.shape}")

Classes: 
[0 1 2 3 4 5 6 7 8 9]
train_targets: 
[0 0 0 ... 9 9 9], shape: (60000,)
train_set: 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape: (60000, 784)
test_targets: 
[0 0 0 ... 9 9 9], shape: (10000,)
test_set: 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape: (10000, 784)


## Generating PCA/LDA data
From previous exercises we already know how to use PCA/LDA.
We first fit a PCA/LDA model to our training data, and then transform the training and test data using this model, to get a dimensionality reduced data set.

In [3]:
n_components = 9

# PCA
pca = PCA(n_components=n_components)
pca.fit_transform()(train_set)
print(f"PCA shape: {pca.shape}")

# LDA
lda = LDA(n_components=n_components)
lda.fit_transform()(train_set, train_targets)
print(f"LDA shape: {lda.shape}")

TypeError: PCA.fit_transform() missing 1 required positional argument: 'X'

## Creating and Training MLP
Sklearn has a multilayer perceptron classifier which we can use:
https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html 

To use it, we need to choose how many layers we would like to use and the size of each hidden layer. 
We can also choose which non-linear activation function to use and what optimizer/solver to use.
You can set a maximum iteration number as well (to limit compute time).

### Model trained on LDA data

In [ ]:
# Instantiate MLP with your parameters of choice and train it on the LDA dimensionality reduced training data.
# Afterwards test it on the test data

### Model trained on PCA data

In [ ]:
# Instantiate MLP with your parameters of choice and train it on the PCA dimensionality reduced training data.
# Afterwards test it on the test data

## Comparing the trained models
With models trained on both LDA and PCA data, let's compare them using the confusion matrices.

In [ ]:
#%%Confusion matrix
#Compute the confusion matrices for both MLPs (trained on PCA and LDA) and plot

### What can we conclude from the comparison?
